### ISSUE TITLE
Growing UI dialogs

### ISSUE THREAD

**Issue by sintopek** [ninjapiraatti/poc-rust-vue#76] opened 2021-08-08 09:04 UTC
Go to your profile.
Add a reservation to your self
edit it (press submit)
edit it again
-> Now your edit dialog has the contents twice.

**Comment by ninjapiraatti** [comment] 2021-08-09 03:32
Unable to reproduce locally or in demo. I fixed this issue earlier, is it still there?

**Comment by sintopek** [comment] 2021-08-09 04:37
is still there.

**Comment by dbfseventsd** [comment] 2021-08-11 09:45
I can't reproduce this locally neither. Tried on Safari and Firefox.

**Comment by ninjapiraatti** [comment] 2021-08-11 10:11
Informed Tuukka on how to reproduce.

**Comment by dbfseventsd** [comment] 2021-08-12 07:27
Fixed in 716775c.

**Closed as completed by dbfseventsd** 2021-08-12 07:27 UTC
